### ISSUE TITLE
do you have the setter counterpart laying around?

### ISSUE THREAD

**Issue by matthewmueller** [developit/dlv#1]
Love this library, but in the market for a tiny setter too.

**Comment by developit** [comment]
I believe so, will check.

**Comment by matthewmueller** [comment]
ping – otherwise i'll write one :-)

**Comment by robinvdvleuten** [comment]
@matthewmueller @developit do one of you had the time for the setter counterpart? Would be really nice 👍

**Comment by kalmbach** [comment]
@matthewmueller @robinvdvleuten @developit  
attempt to build a setter counterpart: https://www.npmjs.com/package/bury

**Comment by robinvdvleuten** [comment]
@kalmbach I did the same to both get and set a property (https://github.com/robinvdvleuten/shvl). The getter testcases may look familiar with this library haha. I currently use it in a fairly popular Vue.js plugin of mine and haven't received any issues thus far 😎
