### ISSUE TITLE
types (TypeScript)

### ISSUE THREAD

**Issue by chodorowicz** [developit/dlv#18]
Hey! 👋

Thanks for this little gem 💎

I'm wondering are you open to committing TS type declaration to the repo? Or should I add them to DefinitelyTyped repo?

**Comment by developit** [comment]
I'd be happy to have them here!  It's probably quite a difficult definition to write since the keypath argument is so opaque though.

**Comment by chodorowicz** [comment]
I've just found a [comment by Daniel Rossenwasser](https://twitter.com/drosenwasser/status/981722403033309185) that preferable way for non TS libraries is to add types to DefinitelyTyped. I will try to do that!

**Comment by chodorowicz** [comment]
Cool 👍

**Comment by ryansonshine** [comment]
@developit , you can close this issue now

**Comment by developit** [comment]
thanks all!
