### ISSUE TITLE
It does not support keys with dots

### ISSUE THREAD

**Issue by simonepri** [developit/dlv#22]
If you have an object like this:
```js
const obj = {
  'hello.word': 'Hello Word'
};
```
You cannot access to the string with that package.

See https://github.com/sindresorhus/dot-prop

**Comment by hustcc** [comment]
```js
get(obj, [pathWithDot]);
```

**Comment by developit** [comment]
Thanks @hustcc - that's correct. For dotted keys, use an Array keypath:

```js
dlv(obj, ['hello.word']);
```
