### ISSUE TITLE
130 bytes is smallest possible?

### ISSUE THREAD

**Issue by Danny-Engelman** [developit/dlv#26]
If you make a statement like that you can always count on a smart ass to respond

* p can be declared as default value
* split('.') can be written as split\`.\`
* length is used twice

How about something like:

```
export default dlv = (
    obj,
    key,
    def,
    p=0,
    k=key.split ? key.split`.` : key,
    l=k.length
) => {
           while (obj && p<l) obj = obj[k[p++]];
           return (obj===undefined || p<l) ? def : obj;   
}
```

... haven't tested it

Or to get rid of the return

```
export default dlv = (
    obj,
    key,
    def,
    p=0,
    k=key.split ? key.split`.` : key,
    l=k.length,
    o=(_=>{while (obj && p<l) obj = obj[k[p++]]})()
) => (obj===undefined || p<l) ? def : obj;
```

**Comment by developit** [comment]
You've confused the statement made: 130b is the ES5 size, which is what most folks actually end up using. The size of the source code is irrelevant, since nobody ships it over the wire.
